name: BetterVoting
description: A better voting plugin for PocketMine-MP

main: Twisted\BetterVoting\BetterVoting
version: 1.7
api: 3.0.0

author: Twisted

commands:
  vote:
    description: Claim your vote reward
