name: BetterVoting
description: A better voting plugin for PocketMine-MP

main: twisted\bettervoting\BetterVoting
version: 2.0.1
api: 3.0.0
softdepend: PiggyCustomEnchants

author: Twisted

permissions:
    bettervoting.command.reload:
        default: op
